# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

isbalancedcpp <- function(M) {
    .Call('_conleyreg_isbalancedcpp', PACKAGE = 'conleyreg', M)
}

haversine_mat <- function(coords, n_obs) {
    .Call('_conleyreg_haversine_mat', PACKAGE = 'conleyreg', coords, n_obs)
}

XeeXhC <- function(distances, X, e, n_obs_t, n_vars) {
    .Call('_conleyreg_XeeXhC', PACKAGE = 'conleyreg', distances, X, e, n_obs_t, n_vars)
}

lp_filling <- function(distances, X, e, n_obs_t, n_vars) {
    .Call('_conleyreg_lp_filling', PACKAGE = 'conleyreg', distances, X, e, n_obs_t, n_vars)
}

time_dist <- function(times, lag_cutoff, X, res, n_obs_u, n_vars) {
    .Call('_conleyreg_time_dist', PACKAGE = 'conleyreg', times, lag_cutoff, X, res, n_obs_u, n_vars)
}

lp_vcov <- function(V, filling, n_vars) {
    .Call('_conleyreg_lp_vcov', PACKAGE = 'conleyreg', V, filling, n_vars)
}

