# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

isbalancedcpp <- function(M) {
    .Call(`_conleyreg_isbalancedcpp`, M)
}

haversine_mat_b <- function(coords, n_obs, dist_cutoff) {
    .Call(`_conleyreg_haversine_mat_b`, coords, n_obs, dist_cutoff)
}

haversine_mat_u <- function(coords, n_obs, dist_cutoff) {
    .Call(`_conleyreg_haversine_mat_u`, coords, n_obs, dist_cutoff)
}

haversine_spmat_b <- function(coords, n_obs, dist_cutoff) {
    .Call(`_conleyreg_haversine_spmat_b`, coords, n_obs, dist_cutoff)
}

haversine_spmat_u <- function(coords, n_obs, dist_cutoff) {
    .Call(`_conleyreg_haversine_spmat_u`, coords, n_obs, dist_cutoff)
}

haversine_spmat_b_bi <- function(coords, n_obs, dist_cutoff) {
    .Call(`_conleyreg_haversine_spmat_b_bi`, coords, n_obs, dist_cutoff)
}

haversine_spmat_u_bi <- function(coords, n_obs, dist_cutoff) {
    .Call(`_conleyreg_haversine_spmat_u_bi`, coords, n_obs, dist_cutoff)
}

XeeXhC_b <- function(distances, X, e, n_obs_t, n_vars) {
    .Call(`_conleyreg_XeeXhC_b`, distances, X, e, n_obs_t, n_vars)
}

XeeXhC_u <- function(distances, X, e, n_obs_t, n_vars) {
    .Call(`_conleyreg_XeeXhC_u`, distances, X, e, n_obs_t, n_vars)
}

XeeXhCsp_b <- function(distances, X, e, n_obs_t, n_vars) {
    .Call(`_conleyreg_XeeXhCsp_b`, distances, X, e, n_obs_t, n_vars)
}

haversine_mat_XeeXhC_b <- function(coords, n_obs, dist_cutoff, X, e, n_vars) {
    .Call(`_conleyreg_haversine_mat_XeeXhC_b`, coords, n_obs, dist_cutoff, X, e, n_vars)
}

haversine_mat_XeeXhC_u <- function(coords, n_obs, dist_cutoff, X, e, n_vars) {
    .Call(`_conleyreg_haversine_mat_XeeXhC_u`, coords, n_obs, dist_cutoff, X, e, n_vars)
}

haversine_spmat_XeeXhC_b <- function(coords, n_obs, dist_cutoff, X, e, n_vars) {
    .Call(`_conleyreg_haversine_spmat_XeeXhC_b`, coords, n_obs, dist_cutoff, X, e, n_vars)
}

haversine_spmat_XeeXhC_u <- function(coords, n_obs, dist_cutoff, X, e, n_vars) {
    .Call(`_conleyreg_haversine_spmat_XeeXhC_u`, coords, n_obs, dist_cutoff, X, e, n_vars)
}

haversine_spmat_XeeXhC_b_bi <- function(coords, n_obs, dist_cutoff, X, e, n_vars) {
    .Call(`_conleyreg_haversine_spmat_XeeXhC_b_bi`, coords, n_obs, dist_cutoff, X, e, n_vars)
}

haversine_spmat_XeeXhC_u_bi <- function(coords, n_obs, dist_cutoff, X, e, n_vars) {
    .Call(`_conleyreg_haversine_spmat_XeeXhC_u_bi`, coords, n_obs, dist_cutoff, X, e, n_vars)
}

lp_filling <- function(distances, X, e, n_obs_t, n_vars) {
    .Call(`_conleyreg_lp_filling`, distances, X, e, n_obs_t, n_vars)
}

haversine_mat_lp_b <- function(coords, X, e, n_obs, n_vars, dist_cutoff) {
    .Call(`_conleyreg_haversine_mat_lp_b`, coords, X, e, n_obs, n_vars, dist_cutoff)
}

haversine_mat_lp_u <- function(coords, X, e, n_obs, n_vars, dist_cutoff) {
    .Call(`_conleyreg_haversine_mat_lp_u`, coords, X, e, n_obs, n_vars, dist_cutoff)
}

haversine_spmat_lp_b <- function(coords, X, e, n_obs, n_vars, dist_cutoff) {
    .Call(`_conleyreg_haversine_spmat_lp_b`, coords, X, e, n_obs, n_vars, dist_cutoff)
}

haversine_spmat_lp_u <- function(coords, X, e, n_obs, n_vars, dist_cutoff) {
    .Call(`_conleyreg_haversine_spmat_lp_u`, coords, X, e, n_obs, n_vars, dist_cutoff)
}

haversine_spmat_lp_b_bi <- function(coords, X, e, n_obs, n_vars, dist_cutoff) {
    .Call(`_conleyreg_haversine_spmat_lp_b_bi`, coords, X, e, n_obs, n_vars, dist_cutoff)
}

haversine_spmat_lp_u_bi <- function(coords, X, e, n_obs, n_vars, dist_cutoff) {
    .Call(`_conleyreg_haversine_spmat_lp_u_bi`, coords, X, e, n_obs, n_vars, dist_cutoff)
}

time_dist <- function(times, lag_cutoff, X, res, n_obs_u, n_vars) {
    .Call(`_conleyreg_time_dist`, times, lag_cutoff, X, res, n_obs_u, n_vars)
}

lp_vcov <- function(V, filling, n_vars) {
    .Call(`_conleyreg_lp_vcov`, V, filling, n_vars)
}

